platform :ios, '9.0'
use_frameworks!

target 'CityOSAir' do
    pod 'Charts'
    pod 'RealmSwift'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Firebase/Messaging'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
